from tkinter import *
win = Tk()

win.geometry("350x517+300+300")
win.title("Calculator")

threelines = Button(win, text="≡", font=("Segoeu UI",15), relief=FLAT)
threelines.place(x=10, y=7)
mode = Label(win, text="Scientific", fg="Blue", font=("Segoe UI", 15))
mode.place(x=45, y=7)
number0 = Label(win, text="0", fg="Black", font=("Segoe UI", 40))
number0.place(x=300, y=30)
DEG = Button(win, text="DEG", font=("Segoeu UI",12), relief=FLAT)
DEG.place(x=10, y=110)
FE = Button(win, text="F-E", font=("Segoeu UI",12), relief=FLAT)
FE.place(x=70, y=110)
MC = Button(win, text="MC", fg="Gray",font=("Segoeu UI",12), relief=FLAT)
MC.place(x=13, y=150)
MR = Button(win, text="MR", fg="Gray",font=("Segoeu UI",12), relief=FLAT)
MR.place(x=70, y=150)
Mplus = Button(win, text="M+", font=("Segoeu UI",12), relief=FLAT)
Mplus.place(x=127, y=150)
Mminus = Button(win, text="M-", font=("Segoeu UI",12), relief=FLAT)
Mminus.place(x=184, y=150)
MS = Button(win, text="MS", font=("Segoeu UI",12), relief=FLAT)
MS.place(x=241, y=150)
Mdown = Button(win, text="M⌄", font=("Segoeu UI",12), relief=FLAT)
Mdown.place(x=298, y=150)
Second = Button(win, text="2nd", font=("Segoeu UI", 10), relief=RAISED, padx=18.5, pady=10)
Second.place(x=1, y=190)
Pi = Button(win, text="π", font=("Segoeu UI", 10), relief=RAISED, padx=24.4, pady=10)
Pi.place(x=70, y=190)
e = Button(win, text="e", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
e.place(x=138, y=190)
C = Button(win, text="C", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
C.place(x=204, y=190)
Delete = Button(win, text="DEL", font=("Segoeu UI", 10), relief=RAISED, padx=20, pady=10)
Delete.place(x=274, y=190)
xsquared = Button(win, text="x^2", font=("Segoeu UI", 10), relief=RAISED, padx=20, pady=10)
xsquared.place(x=1, y=235)
onehalfx = Button(win, text="1/x", font=("Segoeu UI", 10), relief=RAISED, padx=20, pady=10)
onehalfx.place(x=69, y=235)
absval = Button(win, text="|x|", font=("Segoeu UI", 10), relief=RAISED, padx=22, pady=10)
absval.place(x=138, y=235)
exp = Button(win, text="exp", font=("Segoeu UI", 10), relief=RAISED, padx=19, pady=10)
exp.place(x=204, y=235)
mod = Button(win, text="mod", font=("Segoeu UI", 10), relief=RAISED, padx=20, pady=10)
mod.place(x=274, y=235)
squarerootofx = Button(win, text="√x", font=("Segoeu UI", 10), relief=RAISED, padx=22, pady=10)
squarerootofx.place(x=1, y=280)
openparenthesis = Button(win, text="(", font=("Segoeu UI", 10), relief=RAISED, padx=27, pady=10)
openparenthesis.place(x=70, y=280)
closeparenthesis = Button(win, text=")", font=("Segoeu UI", 10), relief=RAISED, padx=26.5, pady=10)
closeparenthesis.place(x=137, y=280)
nexclamation = Button(win, text="n!", font=("Segoeu UI", 10), relief=RAISED, padx=24, pady=10)
nexclamation.place(x=205, y=280)
division = Button(win, text="÷", font=("Segoeu UI", 10), relief=RAISED, padx=29, pady=10)
division.place(x=274, y=280)
xraisetoy = Button(win, text="x^y", font=("Segoeu UI", 10), relief=RAISED, padx=20, pady=10)
xraisetoy.place(x=1, y=326)
seven = Button(win, text="7", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
seven.place(x=70, y=326)
eight = Button(win, text="8", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
eight.place(x=138, y=326)
nine = Button(win, text="9", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
nine.place(x=206, y=326)
x = Button(win, text="x", font=("Segoeu UI", 10), relief=RAISED, padx=29, pady=10)
x.place(x=274, y=326)
tenraisetox = Button(win, text="10^x", font=("Segoeu UI", 10), relief=RAISED, padx=16, pady=10)
tenraisetox.place(x=2, y=373)
four = Button(win, text="4", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
four.place(x=70, y=373)
five = Button(win, text="5", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
five.place(x=138, y=373)
six = Button(win, text="6", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
six.place(x=206, y=373)
minus = Button(win, text="-", font=("Segoeu UI", 10), relief=RAISED, padx=30, pady=10)
minus.place(x=274, y=373)
log = Button(win, text="log", font=("Segoeu UI", 10), relief=RAISED, padx=19.8, pady=10)
log.place(x=3, y=420)
one = Button(win, text="1", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
one.place(x=70, y=420)
two = Button(win, text="2", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
two.place(x=138, y=420)
three = Button(win, text="3", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
three.place(x=206, y=420)
plus = Button(win, text="+", font=("Segoeu UI", 10), relief=RAISED, padx=28, pady=10)
plus.place(x=274, y=420)
ln = Button(win, text="ln", font=("Segoeu UI", 10), relief=RAISED, padx=23.2, pady=10)
ln.place(x=3, y=468)
plusminus = Button(win, text="+/-", font=("Segoeu UI", 10), relief=RAISED, padx=20, pady=10)
plusminus.place(x=71, y=468)
zero = Button(win, text="0", font=("Segoeu UI", 10), relief=RAISED, padx=25, pady=10)
zero.place(x=138, y=468)
period = Button(win, text=".", font=("Segoeu UI", 10), relief=RAISED, padx=26, pady=10)
period.place(x=207, y=468)
equals = Button(win, text="=", font=("Segoeu UI", 10), relief=RAISED, padx=28, pady=10)
equals.place(x=274, y=468)
win.mainloop()